repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-contributor-strategy

  # Updates the default branch for this repository.
  default_branch: main

  # A short description of the repository that will show up on GitHub
  description: CNCF Technical Advisory Group on Contributor Strategy -- maintainer relations, building up contributors, governance, graduation, and more.

  # A URL with more information about the repository
  homepage: https://contribute.cncf.io/

# Collaborators: give specific users access to this repository.
# Note that the permissions are controlled in the https://github.com/cncf/people/blob/main/config.yaml file
# Please create a PR in the https://github.com/cncf/people/ repo to change user access


labels:
  - name: new-wg
    color: 228b22
  - name: infra
    color: 000080
  - name: help wanted
    color: ffff54
  - name: good first issue
    color: ff8c00
  - name: meeting
    color: 00ff00
  - name: wg/governance
    color: 2f4f4f
  - name: wg/maintainers-circle
    color: 00ffff
  - name: wg/contribgrowth
    color: ff00ff
  - name: needs-toc-approval
    description: Requires approval from the TOC before merging to main
    color: b60205
  - name: needs-liaison-approval
    description: Requires approval from TOC liaisons before merging
    color: 750204
  - name: inclusiveness
    color: ffdab9
  - name: comminfra
    color: 1e90ff
  - name: mentoring
    color: 7f0000
  - name: administration
    color: b059ec
  - name: website
    color: f18d0f
  - name: accessibility
    color: 8C0459
  - name: deaf/hoh
    color: C61B7A
  - name: project-level-review
    color: B60205

# additional colors in this palette:
# ff69b4
