repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-contributor-strategy

  # Updates the default branch for this repository.
  default_branch: main

  # A short description of the repository that will show up on GitHub
  description: CNCF Technical Advisory Group on Contributor Strategy -- maintainer relations, building up contributors, governance, graduation, and more.

  # A URL with more information about the repository
  homepage: https://cncf.io/projects

# Collaborators: give specific users access to this repository.
# Note that the permissions below may provide wider access than needed for
# a specific role, and we trust these individuals to act according to their
# role. If there are questions, please contact one of the chairs.
collaborators:
  # Admins
  - username: cathpag
    permission: admin

  - username: geekygirldawn
    permission: admin

  - username: jberkus
    permission: admin

  - username: amye
    permission: admin

  - username: caniszczyk
    permission: admin

#  - username: idvoretskyi
#    permission: admin
    
  - username: carolynvs
    permission: admin

  # Contributors
  # all permissions except admin
  
  - username: mrbobbytables
    permission: push
  
  - username: justaugustus
    permission: push

  - username: parispittman
    permission: push

  - username: gerred
    permission: push

  - username: mattklein123
    permission: push

  - username: thisisnotapril
    permission: push

  - username: karenhchu
    permission: push

  - username: dims
    permission: push

  - username: iennae
    permission: push

  - username: LFCIBot
    permission: push

  # Current TOC liaisons
  - username: TheFoxAtWork
    permission: push
  
  - username: dzolotusky
    permission: push

  # burnout forum and inclusiveness leads
  - username: juliasimon
    permission: push

  - username: mcgonagle
    permission: push
    
  - username: melaniadeangelis
    permission: push
    
  - username: SaraTrap
    permission: push
    
  - username: jadeapplegate
    permission: push
    
    
# mentoring leads

  - username: nate-double-u
    permission: push
    
  - username: jaytiaki
    permission: push

# comminfra leads

  - username: hh
    permission: push
    
# collaborators. see https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

  - username: aliok
    permission: triage

labels:
  - name: new-wg
    color: 228b22
  - name: infra
    color: 000080
  - name: help wanted
    color: ffff54
  - name: good first issue
    color: ff8c00
  - name: meeting
    color: 00ff00
  - name: wg/governance
    color: 2f4f4f
  - name: wg/maintainers-circle
    color: 00ffff
  - name: wg/contribgrowth
    color: ff00ff
  - name: needs-toc-approval
    description: Requires approval from the TOC before merging to main
    color: b60205
  - name: needs-liaison-approval
    description: Requires approval from TOC liaisons before merging
    color: 750204
  - name: inclusiveness
    color: ffdab9
  - name: comminfra
    color: 1e90ff
  - name: mentoring
    color: 7f0000
  - name: administration
    color: b059ec
  - name: website
    color: f18d0f

# additional colors in this palette:
# ff69b4
